SELECT 
A.TITLE, 
B.BOARD_ID, 
B.REPLY_ID, 
B.WRITER_ID,
B.CONTENTS, 
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID
WHERE year(A.CREATED_DATE) = 2022
AND month(A.CREATED_DATE) = 10
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC